### ISSUE TITLE
Should potentially throw errors if theres tabs in the file

### ISSUE THREAD

**Issue by JPinkney** [mulesoft-labs/yaml-ast-parser#12]
Currently if there is tabs in the file the load function will not function correctly. I suggest throwing an error on tabs in the file or converting tabs to spaces automatically in the file.

If this already exists then is there any documentation for it

**Comment by KonstantinSviridov** [comment]
HI, @JPinkney 

We are not going to throw errors on tabs because even in such case we are interested in the parsing process finishing and returning AST.

But nothing prohibits us from creating a `YAMLException` instance and registering it in the `YAMLNode.errors` array. So, for each tab occurence the array is going to contain a separate error object, which can be treated as warning as it has its `isWarning` property set to `true`.

As this functionality breakes the [RAML parser](https://github.com/raml-org/raml-js-parser-2) buildability, it is for now contributed into the `develop` branch. It will be transfered to `master`  with the nearest parser release.

Regards,
Konstantin
